### PR TITLE
Jsonargs

### PR DESCRIPTION
**Pull request by psychomario**
#53 
I am an idiot who can't be trusted with git.

### CODE REVIEW

**Comment by mmattioli** [comment]
lol it happens to all of us. Looks good to me! :+1:

**Comment by psychomario** [comment]
Merged, also think I've fixed all the mess I made.

**Comment by mmattioli** [comment]
All good. I'm gonna pull the dev branch and test with all of the changes to make sure everything is smooth.

**Comment by psychomario** [comment]
Excellent, thank you for your help!

**Pull request merged**
