### PR TITLE
Improve Logging

### PR DESCRIPTION
**Pull request by icb-**
Adding a `--verbose <components>` flag between default of almost nothing and `--debug <components>` of everything, including packet contents.

### CODE REVIEW

**Comment by psychomario** [comment]
This looks good. I'm assuming this has been tested?

Can you add to the relevant sections in `README.md` and `DOCUMENTATION.md`?

**Comment by icb-** [comment]
Added documentation in line with what's there for `--debug`. I've tested everything but NBD, which I don't have the capability to test, but the changes there are minimal, and I've verified syntax is ok.

**Comment by psychomario** [comment]
In that case, this looks good. @mmattioli comments?

**Comment by mmattioli** [comment]
If `.debug` has been replaced with `.info` then what are we sending to `.debug`?

**Comment by psychomario** [comment]
Looks like DHCP packet contents, TFTP block count messages

**Comment by mmattioli** [comment]
Makes sense, thanks for the clarification.

**Pull request merged**
