### PR TITLE
CLI Improvements

### PR DESCRIPTION
**Pull request by psychomario**
Debug negation granularity per #82 
Service disabling per #83

### CODE REVIEW

**Comment by mmattioli** [comment]
@psychomario looks like this needs a rebase, would you want to rebase and merge #70 first?

**Comment by psychomario** [comment]
#70 first sounds good to me, it's been rebased and is ready

**Comment by mmattioli** [comment]
@psychomario one this is rebased, just let me know. Thanks.

**Comment by psychomario** [comment]
@mmattioli Rebased and ready to go.

**Comment by mmattioli** [comment]
:+1:

**Comment by psychomario** [comment]
Am I safe to delete the following branches now?:

 * `nbd`
 * `optionnegation`
 * `staticassignments`

**Comment by mmattioli** [comment]
@psychomario looks like we're completed all of the fixes/patches for v1.6 so I'm going to open another PR for cleanup sometime today. Hold off on deleting those branches for now just incase?

**Comment by psychomario** [comment]
@mmattioli Sure, sounds good to me.

**Comment by mmattioli** [comment]
@psychomario you can delete those branches now that we've cleanly merged

**Comment by psychomario** [comment]
Aha, I just posted an issue regarding this. I'll delete it and delete the branches now.

**Pull request merged**
