### PR TITLE
Default DHCP broadcast changed to ''. It will be derived from IP and subnet mask, unless set explicitly in CLI or config file.

### LINKED ISSUE #132: Default DHCP_BROADCAST doesn't work on multi-NIC servers
The environment is python 2.7.6 and Ubuntu 14.04 server amd64.

I don't think this is a bug, but it doesn't work out-of-the-box on a server with multiple NICs.

I have a server with eth0  and eth1. eth0 runs a DHCP client in 172.16.0.0/16. I want to use eth1 (192.168.2.2) as a PXE/DHCP server for an internal network. The default DHCP_BROADCAST setting (`'<broadcast>' / 255.255.255.255`) sends the DHCP_OFFER to eth0, not eth1. Clients at eth1 will never get an offer.

### PR DESCRIPTION
**Pull request by lqu**
Fixes #132  

Originally, it was `<broadcast>`, which means `255.255.255.255`.
If the server has multiple NICs (e.g. eth0/172.16.0.1, eth1/192.168.2.2),
'255.255.255.255' will send the DHCP_OFFER to the wrong port (eth0). The DHCP client at eth1 will never get an offer.

### CODE REVIEW

**Comment by mmattioli** [comment]
I feel like this is something that should be documented rather than hardcode an arbitrary value. @psychomario, thoughts?

**Comment by psychomario** [comment]
We saw this issue in #25 and the solution was merged from #28. In my (limited) experience, `<broadcast>` is the more generally applicable default (most servers have one nic), and for those cases where it's not the user can specify `--dhcp-broadcast`.

For this specific default, it would be unusable for me, as my LAN is 192.168.0.0/24, and all the other networks I touch are 10/8. I think it would be a bad idea to choose an arbitrary network (192.168.2.0/24) for our defaults.

An acceptable half way could be to take `--dhcp-server-ip` and `--dhcp-subnet` and work out (guess) the broadcast.

As such I agree with @mmattioli, perhaps a section in the README for things you would need to change in a multi-nic environment.

**Comment by lqu** [comment]
@mmattioli @psychomario I agree this is about documentation.

Since there have been hardcoded values (IP, netmask, etc) in the source code already, you need to keep the broadcast part consistent; and if you provide an example, users expect it to work out-of-the box. That's why I changed every occurrence of `<broadcast>`, including readme/example/src. I believe this is the least intrusive way to make it work by default on a multi-NIC server. Changing from `255.255.255.255` to `192.168.2.255` (in accordance with the existing default IP of `192.168.2.2`) shall not break any working code. 

I have three reasons why `192.168.2.255` is better than `<broadcast>` or `255.255.255.255`.

1. It makes PyPXE work by default for multi-NIC servers. All you have to do is choose a NIC and run `ifconfig eth1 192.167.2.2`
2. It is a safer default value. '255.255.255.255' [may go out ](http://www.cs.cmu.edu/~srini/15-441/F01.full/www/assignments/P2/htmlsim_split/node19.html)to a network where there is already a DHCP server, and make your sysadmin mad.
3. It gives an indication that this value should be changed accordingly. '255.255.255.255' seems natural to most people and they may neglect it. `<broadcast>` might be ambiguous unless you read Python `socket` [documentation](https://docs.python.org/2/library/socket.html). '192.168.2.255' forces you to change it if you already changed the default IP.

In enterprise data centers, it is common to have multiple networks, thus mulitple NICs to separate management, data, and maybe IPMI traffic. There may be multiple DHCP servers, and things get more complex when SDN is used. I'm not sure if such servers qualify for 'most servers', but I suspect this is a market with bigger values. When I had this problem #132, the config JSON file with `<broadcast>` looked alright to me. I had to read the source files and run`tcpdump -i eth1 udp port 67 or 68` to debug it.

I enjoy using PyPXE.I used to setup the all the PXE servers manually. XCAT is heavyweight and has a steep learning curve. I hope more people can appreciate the value of PyPXE, where you didn't expect.

**Comment by lqu** [comment]
I like your idea of a derived broadcast address from IP and subnet.

`import socket, struct`
`# 192.168.2.2/24`
`ip = 0xc0a80202`
`mask = 0xffffff00`
` broadcast = (ip & mask) | ((~ mask) & 0xffffffff)`
`print socket.inet_ntoa(struct.pack(">L", broadcast))`

**Comment by psychomario** [comment]
I personally prefer having no default and then deriving it as above. Although we would use the netmask rather than a CIDR.

I do agree that the current behaviour of using 255.255.255.255 and silently failing if the default route is wrong is not very good.

Are you able to create a new PR, with empty defaults for the broadcast and some deriving code if it's not set either on the CLI or via the config file? If not I may get some time tomorrow, or it could be a while until I get chance.

**Comment by lqu** [comment]
@psychomario By "empty defaults", I assume you mean "missing key", instead of "value is empty" or any other placeholder. I'm working on it.

**Comment by lqu** [comment]
What about making the default back to '255.255.255.255'? 

When the DHCP server sees this, it changes it to the derived one? If the value is set in CLI or config file, no change is needed.

**Comment by psychomario** [comment]
Either 255.255.255.255 or '' would work. I prefer '' because you can say '`if not args.DHCP_BROADCAST`'. I think if we're never actually using `255.255.255.255` because it's always derived, it may be sensible to never reference it anywhere. If I see a default of `255.255.255.255` I expect that, not `192.168.2.255`.

**Comment by lqu** [comment]
Yeah, the `''` empty string is also consistent with others (NETBOOT_FILE, NBD_BLOCK_DEVICE, MODE_DEBUG, MODE_VERBOSE). I'm working on it.

**Comment by lqu** [comment]
Please review the changes.

**Comment by lqu** [comment]
I made some change. Please review.

@psychomario Do you want me to close this one and start a new one?

**Comment by mmattioli** [comment]
@lqu please open a new PR against `development` and squash your commits into one; also make sure your commit message contains the string "fixes <issue num>" so that it is auto-closed when merged to `master`. Thanks.

**Pull request closed without merging**
