### PR TITLE
Privilege Dropping

### PR DESCRIPTION
**Pull request by psychomario**
Changed threads to processes to fix permission issues (changing in one thread applies to all)

`setgid` is before `setuid` becuase dropping `uid` may stop dropping `gid`

### CODE REVIEW

**Comment by icb-** [comment]
Using [`pwd.getpwuid`](https://docs.python.org/2/library/pwd.html#pwd.getpwuid) and [`grp.getgrgid`](https://docs.python.org/2/library/grp.html#grp.getgrgid) to resolve symbolic user and group names might be preferable, but from a quick glance this should work.

**Comment by psychomario** [comment]
I've added user/group names and `README.md` info.

**Comment by icb-** [comment]
Not every OS has `root` as a group. Linux generally does, but FreeBSD doesn't. Starting this without passing a group fails to start on FreeBSD.

    [root@icb:~/PyPXE-icb] # python -m pypxe.server
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/root/PyPXE-icb/pypxe/server.py", line 327, in <module>
        main()
      File "/root/PyPXE-icb/pypxe/server.py", line 213, in main
        args.DROP_GID = grp.getgrnam(args.DROP_GRP).gr_gid
    KeyError: 'getgrnam(): name not found: root'
    1z [root@icb:~/PyPXE-icb] 1 # python -m pypxe.server --group nobody
    2015-06-05 12:51:49,914 [INFO] PyPXE Starting TFTP server...
    2015-06-05 12:51:49,916 [INFO] PyPXE PyPXE successfully initialized and running!
    ^C
    Shutting down PyPXE...
    
    Process Process-1:
    Traceback (most recent call last):
    1z [root@icb:~/PyPXE-icb] 1 # id
    uid=0(root) gid=0(wheel) groups=0(wheel),5(operator)
    1z [root@icb:~/PyPXE-icb] #

**Comment by psychomario** [comment]
Am I safe to use 0 as a default GID though?

**Comment by psychomario** [comment]
I think I've fixed this. We only resolve the name if it's not the default.

**Comment by icb-** [comment]
AFAIK, `0` should be safe, but maybe it's better to only drop if user/uid and/or group/gid are specified?

**Comment by psychomario** [comment]
I'm not sure how to do that without another flag, and that seems excessive. 'dropping' to 0 has no effect so is safe as long as uid/gid 0 exists. Using `os.getuid`/`os.getgid` as the defaults might work well. On my system they return 0 but we know it would be safe to `set{uid,gid}` to the return value.

**Comment by psychomario** [comment]
Closed per #108

**Pull request closed without merging**
