### PR TITLE
Merge Gitter badge into development branch

### PR DESCRIPTION
**Pull request by icb-**
The Gitter badge got committed against master, not development.

### CODE REVIEW

**Comment by mmattioli** [comment]
@psychomario @icb- why do we have Gitter at all? We're the only three who really collaborate on this project (rarely does someone even open an issue); I really don't think this project is big enough to warrant a Gitter (it doesn't even warrant a wiki yet).

**Comment by icb-** [comment]
We did already help one person in it.

**Comment by mmattioli** [comment]
Forgive me but do you honestly think it's justifiable to have a Gitter when it's been active for about two months and we've only helped one person? I could understand if this project had 10+ people working on it 'round the clock and dozens of people were constantly opening issues for petty little questions and troubleshooting information but this project honestly isn't that big. If someone has an issue they can open an issue in the issue tracker, the entire purpose of the issue tracker is to _track_ issues and having them on record makes it easier in the long-run to reference old requests/conversations.

@psychomario I'm not really sure what your opinion is on this (it's your repo after all) but I really don't see the need for a Gitter at this stage. Personally, I think it should be removed entirely; there's really no need for it.

**Comment by psychomario** [comment]
I have no stronger opinion either way. It could have been useful hence why I accepted the PR, but it hasn't really turned out to be so, so there doesn't see to be a benefit of it staying, and it could cause fragmentation of issues if it stays.

Is it going to be easy to revert the master PR?

**Comment by mmattioli** [comment]
@psychomario if you are on `master` and do a `git revert 33aed498ca8653670e7ed9838d82c6104366dba3 4f65547e6a4d236b9d1cd378c175db861411e9a4` that will revert the last two commits and create a new one which, effectively undoes the changes in those two commits. You can make the commit message something like "removing Gitter badge" or whatever and then you want to push that commit.

**Comment by psychomario** [comment]
Okay, I can't do this until Sunday but I'll make sure to do so then.

**Comment by mmattioli** [comment]
@psychomario I can do it if you'd like?

**Comment by psychomario** [comment]
That would be ideal, thanks.

**Comment by mmattioli** [comment]
:+1: I'll take care of it sometime today.

**Comment by mmattioli** [comment]
@psychomario I reverted the commit which added the Gitter badge. I think you should revoke repository access to gitter-badger and any remove any/all other traces and/or connections from this repo to Gitter.

**Comment by psychomario** [comment]
I've had a look and I don't think gitter has any access that I can see. It was only a PR so I don't think any permissions are gained when merging.

**Comment by mmattioli** [comment]
:+1: I wasn't sure how it found the repo (you gave it access, signed in with your account, etc.) so figured just give it a look over. Thanks.

**Pull request closed without merging**
