### PR TITLE
Various Patches which Complete v1.5

### PR DESCRIPTION
**Pull request by mmattioli**
Proposal
===
Various bug fixes, patches, and improvements which complete v1.5.

Improvements
---
* Global use of `str.format()`
* Added support for configuration of `pypxe-server.py` via JSON file
* Added support for more granular debugging of `pypxe-server.py` so that selected services can be debugged rather than all or none.
* Added support for UEFI boot
* Added support for syslog
* Improved/updated documentation throughout
* TFTP overhaul, increasing stability and scalability

Bug Fixes
---
* CLI options now take precedence over JSON configuration
* HTTP requests are now threaded
* Added support for TFTP server TID
* Added support for TFTP re-transmit and timeout
* DNS servers now correctly present in offers

### CODE REVIEW

**Comment by mmattioli** [comment]
@psychomario let me know when/if you get a chance to start testing.

**Comment by psychomario** [comment]
@mmattioli I'm starting immediately. I'll try and test every combination of the various sections.

**Comment by psychomario** [comment]
HTTP, TFTP and iPXE chainloading seem to work fully under DHCP-Proxy, both separately and in tandem.

I can't test straight DHCP today, but I should be able to get to it tomorrow.

**Comment by mmattioli** [comment]
:+1: Thanks!

**Comment by mmattioli** [comment]
@psychomario I updated the list of bug fixes and improvements included in this PR (and version), look it over when you get a chance and update if I missed something. Thanks.

**Comment by psychomario** [comment]
@mmattioli I've gone through the changes twice and found two small items, but I think that's it.

**Comment by mmattioli** [comment]
Cool, thanks! :+1: I guess all that's left for this is DHCP testing whenever you get to it.

**Comment by psychomario** [comment]
I've just done some DHCP testing. Everything seems to work as expected.

Now that we have the JSON config file, should we be able to negate options such as `--ipxe`, `--http` and `--no-tftp`? If they're turned OFF in the config file, we can turn them on on the CLI, but not the other way round. It's a trivial fix of 6 lines or so (they need to be mutually exclusive groups).

On a similar note, do we want the ability to negate `--debug` arguments? With the upcoming inclusion of NBD we have four services, and I personally think it would be more user friendly to type `--debug all,-dhcp` than `--debug http,tftp,nbd`. Again, this is a relatively trivial feature to add, although it should probably wait until the next PR batch with nbd and static leases -> `master`.

**Comment by mmattioli** [comment]
>Now that we have the JSON config file, should we be able to negate options such as `--ipxe`, `--http` and `--no-tftp`? If they're turned OFF in the config file, we can turn them on on the CLI, but not the other way round. It's a trivial fix of 6 lines or so (they need to be mutually exclusive groups).

I'll open an issue for this and we can make it part of v1.6

>On a similar note, do we want the ability to negate `--debug` arguments? With the upcoming inclusion of NBD we have four services, and I personally think it would be more user friendly to type `--debug all,-dhcp` than `--debug http,tftp,nbd`. Again, this is a relatively trivial feature to add, although it should probably wait until the next PR batch with nbd and static leases -> `master`.

I'll open a separate issue for this and it can be part of v1.6 as well.

**I'm going to push one more commit to change the version information in `__init__.py` to v1.5 and then we can merge this.**

**Comment by psychomario** [comment]
Excellent.
Once the merge has been done I'll create PRs for those two issues.

**Comment by mmattioli** [comment]
@psychomario congrats, we're at v1.5! :smile: 

I'll open the two issues right now but you can make one PR (and hence, one branch) once you have fixes for both. Just be sure that whichever commits actually fix the issues have the phrase "fixes #whatever" so that when they're merged they automatically close the issues.

**Comment by psychomario** [comment]
Thank you for controlling all the merging and tagging!

I've got the first commit ready to go, I just need the issue numbers

**Pull request merged**
