### PR TITLE
Properly handle TFTP sequence wraps.

### PR DESCRIPTION
**Pull request by icb-**

### CODE REVIEW

**Comment by psychomario** [comment]
Good catch on the keeping track of wraps, I would have missed that. Is this tested and ready to be merged?

Out of interest, why are you using TFTP for 200mb files rather than iPXE and HTTP?

**Comment by icb-** [comment]
I've tested it against the tftp client included in FreeBSD, but I haven't given it a full workout.

Running a huge file through TFTP was a misconfiguration. I moved to iPXE and HTTP once I realized what I'd done.

**Comment by psychomario** [comment]
Feel free to misconfigure more often and catch my mistakes, and let me know when this is ready to merge.

**Comment by icb-** [comment]
I think it's good to merge. I've tested booting both the large iso (http://mfsbsd.vx.sk/) and Tiny Core through pxelinux on a QEMU-KVM VM.

**Comment by psychomario** [comment]
@mmattioli Do you think this should be merged to master immediately as it's a large bug?

**Comment by mmattioli** [comment]
I'll create a PR right now just for formality, if you think it's ready to be merged I'll just merge it immediately.

**Comment by psychomario** [comment]
Yes it looks good to me. PR just lets us do a server side merge easily.

**Comment by mmattioli** [comment]
@psychomario the PR is really just as a formality, there are times when pushing certain commits straight to `master` is acceptable but they're very specific situations.

**Comment by mmattioli** [comment]
@icb- thank you for the quick find and fix :+1:

**Pull request merged**
