### PR TITLE
Network Block Device Implementation

### PR DESCRIPTION
**Pull request by psychomario**
### Reasoning

Current booting options with our stack are limited to a large initramfs or similar. This module allows for whole block devices to be exported for read/write.

### Features

 * Copy-on-write, page granularity
   * In memory
   * On disk
 * Multiple client support
 * Copy block device to ram for serving

### Using

A complete Arch Linux system can be booted using this system. [This](https://github.com/mus65/mkinitcpio-nbd) module needs to be added to the initcpio, as instructed [here](https://wiki.archlinux.org/index.php/Diskless_system#Client_installation).

An iPXE configuration script has been provided to show how to use the image once created.

Performance is perfectly acceptable for one client, multiple clients using the copy-on-write mechanism should see similar performance.

### Issues
 * Locking had to be implemented when using the shared block device open file. Seek location is shared between threads, so seeks followed by reads and writes are wrapped in a single shared lock.
 * There are a few debug messages (disk reads/writes) which should be a higher level of debugging, which has yet to be implemented (mentioned in #59)

### Future expansion
 * COW pages in memory or on disk could be compressed to save space in memory or on disk respectively. Overwriting pages causing compression size changes create implementation difficulties for this.

### Merging
I don't want this merged until we've completed #59 and maybe #65 and have updated the master branch with those updates.

I've opened this PR for testing and code quality changes.

### Comparison to NFS
This deals at a significantly lower level than NFS, we really only care about "read x bytes from y offset", or "write data x to y offset", whereas NFS is a complete filesystem. There is many orders of magnitude lower complexity to this system than NFS.

That being said, I will still attempt to complete my NFS server as they have slightly different use cases, and NFS is used for PXE booting more than NBD is.

### CODE REVIEW

**Comment by mmattioli** [comment]
As per our [conversation](https://github.com/psychomario/PyPXE/pull/59#issuecomment-94306273), this will not be merged into `development` until #59 is merged and `development` is merged into `master`. Please keep in mind it may need to be rebased once #59 is merged.

**Comment by psychomario** [comment]
This PR is also now rebased. There are argument change conflicts with #65 so another rebase will be required for whichever is merged second.

This also fixes #80, but I am open to changes. Here is the current output (missing those added in #65)

```

WARNING: Not root. Servers will probably fail to bind.

usage: pypxe-server.py [-h] [--ipxe] [--http] [--no-tftp] [--debug MODE_DEBUG]
                       [--config JSON_CONFIG] [--syslog SYSLOG_SERVER]
                       [--syslog-port SYSLOG_PORT] [--dhcp | --dhcp-proxy]
                       [-s DHCP_SERVER_IP] [-p DHCP_SERVER_PORT]
                       [-b DHCP_OFFER_BEGIN] [-e DHCP_OFFER_END]
                       [-n DHCP_SUBNET] [-r DHCP_ROUTER] [-d DHCP_DNS]
                       [-c DHCP_BROADCAST] [-f DHCP_FILESERVER]
                       [-a NETBOOT_DIR] [-i NETBOOT_FILE]
                       [--nbd NBD_BLOCKDEVICE] [--nbd-write] [--nbd-cow]
                       [--nbd-cowinmem] [--nbd-copytoram]
                       [--nbd-server NBD_SERVER_IP] [--nbd-port NBD_PORT]

Set options at runtime. Defaults are in pypxe-server.py

optional arguments:
  -h, --help            show this help message and exit
  --ipxe                Enable iPXE ROM (default: False)
  --http                Enable built-in HTTP server (default: False)
  --no-tftp             Disable built-in TFTP server, by default it is enabled
                        (default: True)
  --debug MODE_DEBUG    Comma Seperated (http,tftp,dhcp). Adds verbosity to
                        the selected services while they run. Use 'all' for
                        enabling debug on all services (default: )
  --config JSON_CONFIG  Configure from a JSON file rather than the command
                        line (default: )
  --syslog SYSLOG_SERVER
                        Syslog server (default: None)
  --syslog-port SYSLOG_PORT
                        Syslog server port (default: 514)
  -a NETBOOT_DIR, --netboot-dir NETBOOT_DIR
                        Local file serve directory (default: netboot)
  -i NETBOOT_FILE, --netboot-file NETBOOT_FILE
                        PXE boot file name (after iPXE if --ipxe) (default: )

DHCP:
  Arguments relevant to the DHCP server

  --dhcp                Enable built-in DHCP server (default: True)
  --dhcp-proxy          Enable built-in DHCP server in proxy mode (implies
                        --dhcp) (default: False)
  -s DHCP_SERVER_IP, --dhcp-server-ip DHCP_SERVER_IP
                        DHCP Server IP (default: 192.168.2.2)
  -p DHCP_SERVER_PORT, --dhcp-server-port DHCP_SERVER_PORT
                        DHCP Server Port (default: 67)
  -b DHCP_OFFER_BEGIN, --dhcp-begin DHCP_OFFER_BEGIN
                        DHCP lease range start (default: 192.168.2.100)
  -e DHCP_OFFER_END, --dhcp-end DHCP_OFFER_END
                        DHCP lease range end (default: 192.168.2.150)
  -n DHCP_SUBNET, --dhcp-subnet DHCP_SUBNET
                        DHCP lease subnet (default: 255.255.255.0)
  -r DHCP_ROUTER, --dhcp-router DHCP_ROUTER
                        DHCP lease router (default: 192.168.2.1)
  -d DHCP_DNS, --dhcp-dns DHCP_DNS
                        DHCP lease DNS server (default: 8.8.8.8)
  -c DHCP_BROADCAST, --dhcp-broadcast DHCP_BROADCAST
                        DHCP broadcast address (default: <broadcast>)
  -f DHCP_FILESERVER, --dhcp-fileserver DHCP_FILESERVER
                        DHCP fileserver IP (default: 192.168.2.2)

Network Block Device:
  Arguments relevant to the NBD server

  --nbd NBD_BLOCKDEVICE
                        Enable the NDB server with a specific block device
                        (Can be a disk image) (default: )
  --nbd-write           Enable writes on the NBD device (default: False)
  --nbd-cow             Enable copy-on-write for the NBD device (Non-
                        persistent changes) (default: True)
  --nbd-cowinmem        Store copy-on-write pages in memory (default: False)
  --nbd-copytoram       Copy the NBD device to memory before serving clients
                        (default: False)
  --nbd-server NBD_SERVER_IP
                        NBD Server IP (default: 0.0.0.0)
  --nbd-port NBD_PORT   NBD Server Port (default: 10809)
```

Now that we have the JSON config file, do we still want the non-obvious short options for DHCP?

Furthermore, do we still want all of the options in the `usage: ` line at the beginning of the output? We have a lot of options now and this is beginning to get cluttered.

**Comment by mmattioli** [comment]
@psychomario can you just run through the issue tracker and comment with which issues this fixes/closes? I think it closes 2-3 of them but it's missing that in the commit messages so I might have to close them manually. If you leave a list here it makes it easier later. Thanks!

**Comment by psychomario** [comment]
Fixes: #80

**Comment by mmattioli** [comment]
@psychomario all ready to go?

**Comment by psychomario** [comment]
@mmattioli Looks like it, yes

**Pull request merged**
