### PR TITLE
Various Patches which Complete v1.6

### LINKED ISSUE #27: Support Static Assignments, Per-host Options
It would be nice to support static assignment, and sending specific options (and values) to each host. For example, only responding to one specific host is desirable, rather than any PXE DHCP request received.

### LINKED ISSUE #79: DHCPD's listen() is Overly Global
Proposal
===
In DHCPD's `listen()`, the setting of `self.options` and the check using `valid_request` is overly global. We should probably use `self.leases` as we already have `client_mac` to use as the key. `self.options` is used in `listen()`, `valid_request`, and `craft_options`.

A simple` s/self.options/self.leases[client_mac]["options"]/` would actually do the job. Everywhere we access `self.options` we have `client_mac`. (Except `validate_req`, for which we could either pass in `client_mac`, or option 60).

### LINKED ISSUE #80: Improve CLI Argument Groups
Proposal
===
As `--help` is getting quite long now, we could use `parser.add_argument_group()` to split up related sections (e.g `--dhcp-*`, `--netboot-*`).

### LINKED ISSUE #82: Negate Debug Arguments with CLI
Proposal
===
Being able to negate debug arguments allows for greater control of debugging modes.

Example
---
This is preferable usage:

```bash
--debug all,-dhcp
```
...as opposed to current usage:

```bash
--debug http,tftp
```

### LINKED ISSUE #83: Enable/Disable Services with CLI when using JSON Configuration
Proposal
===
Now that we have the JSON config file, we should be able to enable/disable services via CLI when using a JSON file. If they're turned OFF in the config file, we can turn them on on the CLI, but not the other way round.

### LINKED ISSUE #85: Remove Short CLI Options from --help
Only the options for DHCP are available as short options, and half of those aren't very intuitive.

Should we remove all short options and be consistent with long options?

Now we have the JSON config file it's not really required to save on typing as options can be set there.

### PR DESCRIPTION
**Pull request by mmattioli**
Proposal
===
Various bug fixes, patches, and improvements which complete v1.6. This release fixes #85, fixes #83, fixes #82, fixes #80, fixes #79, and fixes #27.

Improvements
---
* Added support for NBD (network block device)
* Added debug mode negation via CLI options
* Removed short CLI options
* Added support for static DHCP lease assignments and DHCP whitelist
* Improved CLI argument groupings to help without output out `--help` in `pypxe-server.py`

Bug Fixes
---
* Now able to enable/disable services via CLI when using a JSON configuration file
* DHCP options are now client-specific

### CODE REVIEW

**Comment by mmattioli** [comment]
@psychomario before we do any actual testing perhaps we should take care of any missing documentation for whatever patches/fixes we have here?

**Comment by psychomario** [comment]
@mmattioli Probably, I was just about to comment regarding this. So far I've noticed that debug negation is missing from `--help` and the README, I'm just about to go through the rest to find other missing sections.

**Comment by psychomario** [comment]
The following kwarg table items are missing from `DOCUMENTATION.md`:

* DHCP
 * `whitelist`
 * `static_config`

I believe that is it. Do you want me to write a section under Background for NBD and a similar table for the kwargs?

**Comment by mmattioli** [comment]
@psychomario yeah if you handle the NBD stuff I'll take care of the DHCP stuff

**Comment by psychomario** [comment]
I've got something written up in #91, accepting any criticism.

**Comment by psychomario** [comment]
Do you think `--dhcp-fileserver` and `--dhcp-whitelist` should be somehow separated from the rest of the `--dhcp-*` arguments, as they are the two that are available in both `--dhcp` and `--dhcp-proxy` modes?

**Comment by mmattioli** [comment]
Not really, if someone has an understanding of how DHCP works then they should have an understanding that these two options would inherently work in both modes.

**Comment by psychomario** [comment]
Fair enough.

**Comment by mmattioli** [comment]
@psychomario is this ready for testing or are we missing something? Pretty sure we should be ready to start testing but just wanted to check with you.

**Comment by psychomario** [comment]
I think we're ready for testing. I'll be able to test everything in the ~morning, although I'm not expecting to find anything as I've been testing as I've been going along.

**Comment by mmattioli** [comment]
Sounds good, let me know if you run into anything because once this is merged and we tag the new release I think we can take a break for a while lol

**Comment by psychomario** [comment]
Well that's all the long standing issues done, except for NFS, which I really ought to get motivated to continue as I have the summer off.

**Comment by psychomario** [comment]
I've done some testing, and my fixes are present in #92, there's also a query regarding log messages. Once that PR is resolved then I think we're ready to be merged.

**Comment by mmattioli** [comment]
@psychomario LGTM Ready to go?

**Comment by psychomario** [comment]
Other than the query in #92, I think so:

With the initial debug logging block, there are a lot of lines that duplicate the service name in the log format string and the actual log message. For example:
```
2015-05-12 17:30:51,190 [DEBUG] PyPXE.TFTP TFTP Server IP: 0.0.0.0
2015-05-12 17:30:51,190 [DEBUG] PyPXE.TFTP TFTP Server Port: 69
2015-05-12 17:30:51,190 [DEBUG] PyPXE.TFTP TFTP Network Boot Directory: .
```
Should we remove the second `TFTP`, as it is already present in the logging namespace?

**Comment by mmattioli** [comment]
@psychomario just fixed, good catch :+1: Ready?

**Comment by psychomario** [comment]
@mmattioli Thanks! I think we're ready now, yes.

**Pull request merged**
